apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-app
  labels:
    app: dev-app
  name: dev-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - image: nginx:1.25.1
        name: dev-app
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
