apiVersion: v1
kind: Service
metadata:
  namespace: dev-app
  labels:
    app: dev-app
  name: dev-app
spec:
  selector:
    app: dev-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32300
    protocol: TCP
